### ISSUE TITLE
attachinterrupt 

### ISSUE THREAD

**Issue by MohitKajla** [hoilett/Arduino-Walkie-Talkie-Instructable#1]
//sets interrupt to check for button talk abutton press
  attachInterrupt(digitalPinToInterrupt(talkButton), talk, CHANGE);

I am getting the error "digitalpintointerrupt" was not decleared in the scope.

**Comment by hoilett** [comment]
Which version of Arduino are you using? And which Arduino board are you using? And make sure you write "digitalPinToInterrupt" and not "digitalpintointerrupt". Please note that capitalization is important here.

**Comment by hoilett** [comment]
I apologize for the late reply. The end of the semester was pretty busy for me.
